# printWidth: 80 # 80
# tabWidth: 2 # 2
# useTabs: false # false
semi: true
singleQuote: true # false
#trailingComma: es5 #none # none | es5 | all
bracketSpacing: false # true
# jsxBracketSameLine: false # false
arrowParens: always
